# Generated by Django 5.0.1 on 2024-01-18 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pe_3_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Estudiante',
            new_name='Alumno',
        ),
        migrations.RenameModel(
            old_name='CursoEstudiantes',
            new_name='CursoAlumnos',
        ),
        migrations.RenameField(
            model_name='cursoalumnos',
            old_name='estudiante',
            new_name='alumno',
        ),
    ]
